name: Create Monday.com Board
env:
 MONDAY_API_KEY: ${{ secrets.MONDAY_TOKEN }}

on: push
   # branches: [ main ]

jobs:
  create-board:
    name: monday_board
    runs-on: ubuntu-latest
    #env:
      #MONDAY_API_KEY: ${{ secrets.MONDAY_TOKEN }}
   
    steps:
    - uses: actions/checkout@v4 

    - name: Create Board
     # env:
     # MONDAY_API_KEY: ${{ secrets.MONDAY_TOKEN }}
      run: |
        # Create a new board
       
        curl -X POST \
          --header "Content-Type: application/json" \
          --header "Authorization: ${{ env.MONDAY_API_KEY }}" \
          --data '{"query": mutation {create_board (board_name: "new_board2", board_kind: public){ id }}' \
          'https://api.monday.com/v2/'

        echo "Created board with ID: "

   # - name: Create Monday.com Card
    #  run: |
     #   MONDAY_API_KEY=${{env.MONDAY_TOKEN}}
      #  BOARD_ID=<REPLACE_WITH_BOARD_ID>
       # ITEM_NAME="New Card"

        # Create a new card
        #curl --request POST \
         # --url 'https://api.monday.com/v2/items' \
          #--header "Content-Type: application/json" \
         # --header "Authorization: ${{env.MONDAY_TOKEN}}" \
         # --data-raw '{
           # "board_id": '"$BOARD_ID"',
          #  "name": "'"$ITEM_NAME"'"
         # }'
